- id: "1720385058845"
  alias: Alexa announce
  description: ""
  trigger: []
  condition: []
  action:
    - service: script.notify_most_alexas
      metadata: {}
      data: {}
  mode: single
- id: "1720455959360"
  alias: Turn off Living Room TV when Owen away
  description: ""
  trigger: []
  condition: []
  action:
    - service: media_player.turn_off
      metadata: {}
      data: {}
      target:
        entity_id: media_player.living_room_tv_2
  mode: single
- id: "1720475177733"
  alias: ios blueprint
  description: ""
  use_blueprint:
    path: Hypercookie/ios_notification_blueprint.yaml
    input:
      trigger_source: input_button.wifi_helper_button
      message_content: Ziegler Test
      message_sound_name: US-EN-Alexa-Garage-Door-Opened.wav
      message_static_media_url: http://www.cnn.com
      dummy: true
      target_for_notifications: mobile_app_iphone703
      action_1_action_enabled: true
      action_1_title: OK?
      action_1_action_activation_mode: foreground
      action_1_action_authentication_required: true
      message_attachment: Static
- id: "1720895026610"
  alias: "\U0001F9ED Extended Zone Notifications -15s"
  description: ""
  use_blueprint:
    path: panhans/zone_notification_extended.yaml
    input:
      persons:
        - person.katharine
        - person.owen
        - person.william
      notify_device: 3e6b468aa8cbb0c2286599eeac0fb952

# Smart Light Off at Switch Alert Automations
- id: "1691234500000"
  alias: "💡❌ Alert - Butler's Pantry Light Off at Switch"
  description: "Alert when Butler's Pantry Light has been turned off at the switch"
  trigger:
    - platform: state
      entity_id: binary_sensor.butlers_pantry_light_off_at_switch
      from: "off"
      to: "on"
  condition: []
  action:
    - service: notify.mobile_app_iphone703
      data:
        message: "💡❌ Butler's Pantry Light has been turned off at the switch"
        data:
          push:
            sound: alarm.caf
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.alexa_butlers_pantry_light_off
    - delay:
        seconds: 5
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.alexa_butlers_pantry_light_off
    - service: logger.info
      data:
        message: "Butler's Pantry Light detected as off at the switch"
  mode: single

- id: "1691234500001"
  alias: "💡❌ Alert - Coat Closet Hall Light Off at Switch"
  description: "Alert when Coat Closet Hall Light has been turned off at the switch"
  trigger:
    - platform: state
      entity_id: binary_sensor.coat_closet_hall_light_off_at_switch
      from: "off"
      to: "on"
  condition: []
  action:
    - service: notify.mobile_app_iphone703
      data:
        message: "💡❌ Coat Closet Hall Light has been turned off at the switch"
        data:
          push:
            sound: alarm.caf
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.alexa_coat_closet_hall_light_off
    - delay:
        seconds: 5
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.alexa_coat_closet_hall_light_off
    - service: logger.info
      data:
        message: "Coat Closet Hall Light detected as off at the switch"
  mode: single

- id: "1691234500002"
  alias: "💡❌ Alert - Garage Back Door Light Off at Switch"
  description: "Alert when Garage Back Door Light has been turned off at the switch"
  trigger:
    - platform: state
      entity_id: binary_sensor.garage_back_door_light_off_at_switch
      from: "off"
      to: "on"
  condition: []
  action:
    - service: notify.mobile_app_iphone703
      data:
        message: "💡❌ Garage Back Door Light has been turned off at the switch"
        data:
          push:
            sound: alarm.caf
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.alexa_garage_back_door_light_off
    - delay:
        seconds: 5
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.alexa_garage_back_door_light_off
    - service: logger.info
      data:
        message: "Garage Back Door Light detected as off at the switch"
  mode: single

- id: "1691234500003"
  alias: "💡❌ Alert - Garage Tool Light Off at Switch"
  description: "Alert when Garage Tool Light has been turned off at the switch"
  trigger:
    - platform: state
      entity_id: binary_sensor.garage_tool_light_off_at_switch
      from: "off"
      to: "on"
  condition: []
  action:
    - service: notify.mobile_app_iphone703
      data:
        message: "💡❌ Garage Tool Light has been turned off at the switch"
        data:
          push:
            sound: alarm.caf
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.alexa_garage_tool_light_off
    - delay:
        seconds: 5
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.alexa_garage_tool_light_off
    - service: logger.info
      data:
        message: "Garage Tool Light detected as off at the switch"
  mode: single

- id: "1691234500004"
  alias: "💡❌ Alert - Kitchen Sink Light Off at Switch"
  description: "Alert when Kitchen Sink Light has been turned off at the switch"
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_sink_light_off_at_switch
      from: "off"
      to: "on"
  condition: []
  action:
    - service: notify.mobile_app_iphone703
      data:
        message: "💡❌ Kitchen Sink Light has been turned off at the switch"
        data:
          push:
            sound: alarm.caf
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.alexa_kitchen_sink_light_off
    - delay:
        seconds: 5
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.alexa_kitchen_sink_light_off
    - service: logger.info
      data:
        message: "Kitchen Sink Light detected as off at the switch"
  mode: single

- id: "1691234500005"
  alias: "💡❌ Alert - Office Lamp Light Off at Switch"
  description: "Alert when Office Lamp Light has been turned off at the switch"
  trigger:
    - platform: state
      entity_id: binary_sensor.office_lamp_light_off_at_switch
      from: "off"
      to: "on"
  condition: []
  action:
    - service: notify.mobile_app_iphone703
      data:
        message: "💡❌ Office Lamp Light has been turned off at the switch"
        data:
          push:
            sound: alarm.caf
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.alexa_office_lamp_light_off
    - delay:
        seconds: 5
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.alexa_office_lamp_light_off
    - service: logger.info
      data:
        message: "Office Lamp Light detected as off at the switch"
  mode: single